name: Makefile CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y astyle cppcheck catch2

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: format_check
      working-directory: ./
      run: ./tools/format.sh --dry

    - name: cpp_check
      working-directory: ./
      run: make cppcheck

    - name: unit_tests
      working-directory: ./
      run: make tests

    - name: release
      working-directory: ./
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: osp2_linux
        path: osp2_linux.tar.gz
        if-no-files-found: error
        retention-days: 5

  mingw:
    name: MinGW GCC
    needs: linux 

    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: release
      working-directory: ./
      run: | 
        make

    - uses: actions/upload-artifact@v4
      with:
        name: osp2_windows
        path: osp2_windows.zip
        if-no-files-found: error
        retention-days: 5

  create-latest:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [linux, mingw]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            osp2_windows
            osp2_linux



