name: Makefile CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y astyle

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: check_format
      working-directory: ./
      run: ./format.sh --dry

    - name: build-qvm
      working-directory: build/qvm
      run: | 
        make

    - name: build-so
      working-directory: build/library
      run: | 
        make

    - uses: actions/upload-artifact@v4
      with:
        name: qvm
        path: build/qvm/zz-osp-pak8.pk3
        if-no-files-found: error
        retention-days: 5

    - uses: actions/upload-artifact@v4
      with:
        name: so
        path: build/library/build/release-linux-x86_64/osp2/cgamex86_64.so
        if-no-files-found: error
        retention-days: 5

  mingw:
    name: MinGW GCC

    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build-qvm
      working-directory: build/qvm
      run: | 
        make

    - name: build-dll
      working-directory: build/library
      run: | 
        make

    - uses: actions/upload-artifact@v4
      with:
        name: dll
        path: build/library/build/release-mingw64-x86_64/osp2/cgamex86_64.dll
        if-no-files-found: error
        retention-days: 5

  create-latest:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [linux, mingw]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            qvm
            so
            dll



